version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - doc-review-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doc-review-backend
    ports:
      - "3001:3001"
    environment:
      - FLASK_ENV=production
      - PORT=3001
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=minio123456
      - MINIO_BUCKET_NAME=pdf-documents
      - MINIO_SECURE=false
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - doc-review-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doc-review-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - doc-review-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  minio_data:

networks:
  doc-review-network:
    driver: bridge

